sonata_admin:
    title: 'Lesptitspoussins'
    templates:
        show: '/Admin/show/show.html.twig'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
