<?php


namespace App\Admin;


use App\Entity\Avis;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class AvisAdmin extends AbstractAdmin
{

    public function toString($object)
    {
        return $object instanceof Avis
            ? $object->getId()
            : 'Avis : ID';
    }

    protected function configureFormFields(FormMapper $form)
    {
        $form
            ->add('note', ChoiceType::class, [
                'multiple' => true,
                'choices' => [
                    'j\'aime' => 'j\'aime',
                    'je n\'aime pas' => 'je n\'aime pas'
                ],
            ])
            ->add('texte')
            ;
    }

    protected function configureListFields(ListMapper $list)
    {
        $list
            ->addIdentifier('id', null, [
                'route' =>
                    [
                'name' => 'show'
            ]])
            ->add('note', 'choice', [
                'multiple' => true,
                'choices' => [
                    'j\'aime' => 'j\'aime',
                    'je n\'aime pas' => 'je n\'aime pas'
                ],
            ])
            ->add('texte')
            ->add('parentt', null, ['associated_property' => 'nom', 'label' => 'Parent'])
            ->add('proProfil', null, ['associated_property' => 'nom_entreprise', 'label' => 'Entrprise'])
            ->add('actions', 'actions', [
                'actions' => [
                    'edit' => [],
                    'delete' => []
                ]
            ])
            ->add('is_enabled')
            ;
    }

    protected function configureDatagridFilters(DatagridMapper $filter)
    {
        $filter
            ->add('id')
            ->add('note')
            ;
    }

    protected function configureShowFields(ShowMapper $show)
    {
        parent::configureShowFields($show); // TODO: Change the autogenerated stub
        $show
            ->add('note', 'choice', [
                'multiple' => true,
                'choices' => [
                    'j\'aime' => 'j\'aime',
                    'je n\'aime pas' => 'je n\'aime pas'
                ],
            ])
            ->add('texte')
            ->add('parentt', null, ['associated_property' => 'nom', 'label' => 'Parent'])
            ->add('proProfil', null, ['associated_property' => 'nom_entreprise', 'label' => 'Entrprise'])
            ->add('created_at')
            ->add('updated_at')
            ->add('is_enabled')
            ;
    }

}