<?php


namespace App\Admin;


use App\Entity\Facturation;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;

class FacturationAdmin extends AbstractAdmin
{

    protected function configureFormFields(FormMapper $form)
    {
        parent::configureFormFields($form); // TODO: Change the autogenerated stub
        $form
            ->add('date')
            ->add('montant_ht')
            ->add('tva')
            ->add('total')
            ;
    }

    protected function configureListFields(ListMapper $list)
    {
        parent::configureListFields($list); // TODO: Change the autogenerated stub
        $list
            ->addIdentifier('id')
            ->add('date')
            ->add('montant_ht')
            ->add('tva')
            ->add('total')
            ;
    }

    protected function configureDatagridFilters(DatagridMapper $filter)
    {
        parent::configureDatagridFilters($filter); // TODO: Change the autogenerated stub
        $filter
            ->add('id')
            ->add('date')
            ;
    }

}