<?php


namespace App\Admin;


use App\Entity\Paiement;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;

class PaiementAdmin extends AbstractAdmin
{

    public function toString($object)
    {
        return parent::toString($object); // TODO: Change the autogenerated stub
        return $object instanceof Paiement
            ? $object->getId()
            : 'ID';
    }

    protected function configureFormFields(FormMapper $form)
    {
        parent::configureFormFields($form); // TODO: Change the autogenerated stub
        $form
            ->add('montant')
            ->add('mode_paiement', null, [
                'label' => 'Moyen de Paiement'
            ])
            ->add('date_paiement', null, [
                'label' => 'Date du Paiement'
            ])
            ;
    }

    protected function configureListFields(ListMapper $list)
    {
        parent::configureListFields($list); // TODO: Change the autogenerated stub
        $list
            ->addIdentifier('id', null, [
                'route' => [
                    'name' => 'show'
                ]
            ])
            ->add('montant')
            ->add('mode_paiement', null, [
                'label' => 'Moyen de Paiement'
            ])
            ->add('date_paiement', null, [
                'label' => 'Date du Paiement'
            ])
            ->add('parentt', null, ['associated_property' => 'nom', 'label' => 'Parent'])
            ->add('proProfil', null, ['associated_property' => 'nom_entreprise', 'label' => 'Entrprise'])
            ->add('actions', 'actions', [
                'actions' => [
                    'edit' => [],
                    'delete' => []
                ]
            ])
        ;
    }

    protected function configureDatagridFilters(DatagridMapper $filter)
    {
        parent::configureDatagridFilters($filter); // TODO: Change the autogenerated stub
        $filter
            ->add('mode_paiement', null, [
                'label' => 'Moyen de Paiement'
            ])
            ->add('date_paiement', null, [
                'label' => 'Date du Paiement'
            ])            ;
    }

    protected function configureShowFields(ShowMapper $show)
    {
        parent::configureShowFields($show); // TODO: Change the autogenerated stub
        $show
            ->add('id')
            ->add('montant')
            ->add('mode_paiement', null, [
                'label' => 'Moyen de Paiement'
            ])
            ->add('date_paiement', null, [
                'label' => 'Date du Paiement'
            ])
            ->add('parentt', null, ['associated_property' => 'nom', 'label' => 'Parent'])
            ->add('proProfil', null, ['associated_property' => 'nom_entreprise', 'label' => 'Entrprise'])
            ->add('created_at')
            ->add('updated_at')
            ;
    }


}