<?php


namespace App\Admin;


use App\Entity\EnfantProfil;
use App\Entity\Parentt;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Form\Type\ModelType;
use Sonata\AdminBundle\Show\ShowMapper;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;

class ParenttAdmin extends AbstractAdmin
{
    public function toString($object)
    {
        return $object instanceof Parentt
            ? $object->getMail()
            : 'Parent';
    }

    protected function configureFormFields(FormMapper $form)
    {
        $form
            ->add('nom')
            ->add('prenom')
            ->add('mail', EmailType::class)
            ->add('ville')
            ->add('codepostal')
            ->add('adresse')
            ->add('enfant', ModelType::class, [
                'class' => EnfantProfil::class,
                'property' => 'nom',
                'mapped' => true,
                'multiple' => true,
                'btn_add' => 'Ajouter',
            ])
            ->add('password', PasswordType::class)
            ->add('is_enabled')
        ;
    }

    protected function configureListFields(ListMapper $list)
    {
        parent::configureListFields($list); // TODO: Change the autogenerated stub
        $list
            ->addIdentifier('nom')
            ->add('prenom')
            ->addIdentifier('mail')
            ->add('ville')
            ->add('codepostal')
            ->add('adresse')
            ->add('enfants', 'model', [
                'class' => EnfantProfil::class,
                'property' => 'nom',
                'mapped' => true
            ])
            ->add('created_at_abonnement')
            ->add('status_abonnement', 'boolean')
            ->add('date_duree')
            ->add('is_enabled', 'boolean')
        ;
    }

    protected function configureDatagridFilters(DatagridMapper $filter)
    {
        parent::configureDatagridFilters($filter); // TODO: Change the autogenerated stub
        $filter
            ->add('nom')
            ->add('ville')
            ->add('codepostal', null,[
                'label' => 'Code Postal'
            ])
        ;
    }

    protected function configureShowFields(ShowMapper $show)
    {
        parent::configureShowFields($show); // TODO: Change the autogenerated stub
        $show
            ->add('nom')
            ->add('prenom')
            ->add('mail')
            ->add('ville')
            ->add('codepostal', null, [
                'label' => 'Code Postal'
            ])
            ->add('adresse')
            ->add('created_at_abonnement', null, [
                'label' => 'Date début abonnement'
            ])
            ->add('status_abonnement', 'boolean', [
                'label' => 'Abonné'
            ])
            ->add('date_duree', null, [
                'label' => 'Durée abonnement'
            ])
            ->add('is_enabled', 'boolean')
        ;
    }

}