<?php


namespace App\Admin;


use App\Entity\Plan;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Symfony\Component\Form\Extension\Core\Type\TimeType;

class PlanAdmin extends AbstractAdmin
{

    public function toString($object)
    {
        return parent::toString($object); // TODO: Change the autogenerated stub
        return $object instanceof Plan
            ? $object->getDate()
            : 'Date';
    }

    protected function configureFormFields(FormMapper $form)
    {
        parent::configureFormFields($form); // TODO: Change the autogenerated stub
        $form
            ->add('date')
            ->add('heuredebut', TimeType::class)
            ->add('heuredefin', TimeType::class)
        ;
    }

    protected function configureListFields(ListMapper $list)
    {
        parent::configureListFields($list); // TODO: Change the autogenerated stub
        $list
            ->addIdentifier('date')
            ->add('heuredebut')
            ->add('heuredefin')
        ;
    }

    protected function configureDatagridFilters(DatagridMapper $filter)
    {
        parent::configureDatagridFilters($filter); // TODO: Change the autogenerated stub
        $filter
            ->add('date')
        ;
    }

}