<?php


namespace App\Admin;


use App\Entity\ProProfil;
use App\Entity\Tuteur;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Form\Type\ModelType;
use Sonata\AdminBundle\Show\ShowMapper;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class ProProfilAdmin extends AbstractAdmin
{
    public function toString($object)
    {
        return $object instanceof ProProfil
            ? $object->getnom_entreprise()
            : 'Nom Entreprise';
    }

    protected function configureFormFields(FormMapper $form)
    {
        parent::configureFormFields($form); // TODO: Change the autogenerated stub
        $form
            ->add('nom_entreprise', TextType::class, [
                'label' => 'Votre Nom d\'Entreprise'
            ])
            ->add('mail', EmailType::class, [
                'label' => 'Votre adresse mail'
            ])
            ->add('adresse', null, [
                'label' => 'Votre Adresse Postal'
            ])
            ->add('ville')
            ->add('codepostal', null, [
                'label' => 'Votre Code Postal'
            ])
            ->add('nombredeplace', null, [
                'label' => 'Le nombre de places total dans votre établissement'
            ])
            ->add('tuteur', ModelType::class, [
                'class' => Tuteur::class,
                'label' => 'Vos Tuteurs',
                'property' => 'nom',
                'multiple' => true,
                'btn_add' => true,

            ])
            ->add('password', PasswordType::class, [
                'label' => 'Votre Mot de Passe'
            ])
            ->add('status', null, [
                'label' => 'Actif'
            ])
        ;
    }

    public function prePersist($object)
    {
        parent::prePersist($object); // TODO: Change the autogenerated stub
        foreach ($object->getTuteur() as $reponse){
            $reponse->setProProfil($object);
        }
    }

    public function preUpdate($object)
    {
        parent::preUpdate($object); // TODO: Change the autogenerated stub
        foreach ($object->getTuteur() as $reponse){
            $reponse->setProProfil($object);
        }
    }

    protected function configureListFields(ListMapper $list)
    {
        parent::configureListFields($list); // TODO: Change the autogenerated stub
        $list
            ->add('id')
            ->addIdentifier('nom_entreprise', null, [
                'label' => 'Votre Nom d\'Entreprise',
                'route' => [
                    'name' => 'show'
                ]
            ])
            ->add('mail', EmailType::class, [
                'label' => 'Votre adresse mail'
            ])
            ->add('adresse', null, [
                'label' => 'Votre Adresse Postal'
            ])
            ->add('ville')
            ->add('codepostal', null, [
                'label' => 'Votre Code Postal'
            ])
            ->add('nombredeplace', null, [
                'label' => 'Le nombre de places total dans votre établissement'
            ])
            ->add('tuteur', null, ['associated_property' => 'nom'])
            ->add('status', null, [
                'label' => 'Actif'
            ])
            ->add('actions', 'actions', [
                'actions' => [
                    'edit' => [],
                    'delete' => []
                ]
            ])
        ;
    }

    protected function configureDatagridFilters(DatagridMapper $filter)
    {
        parent::configureDatagridFilters($filter); // TODO: Change the autogenerated stub
        $filter
            ->add('nom_entreprise', null, [
                'label' => 'Nom d\'Entreprise'
            ])
        ;
    }

    protected function configureShowFields(ShowMapper $show)
    {
        parent::configureShowFields($show); // TODO: Change the autogenerated stub
        $show
            ->add('id')
            ->add('nom_entreprise', TextType::class, [
                'label' => 'Votre Nom d\'Entreprise'
            ])
            ->add('mail', EmailType::class, [
                'label' => 'Votre adresse mail'
            ])
            ->add('adresse', null, [
                'label' => 'Votre Adresse Postal'
            ])
            ->add('ville')
            ->add('codepostal', null, [
                'label' => 'Votre Code Postal'
            ])
            ->add('nombredeplace', null, [
                'label' => 'Le nombre de places total dans votre établissement'
            ])
            ->add('tuteur', null, ['associated_property' => 'nom'])
            ->add('status', null, [
                'label' => 'Actif'
            ])
            ->add('created_at', null, [
                'label' => 'Date de Création de votre compte'
            ])
            ->add('updated_at', null, [
                'label' => 'Date de dernière modification'
            ])
            ;
    }
}