<?php


namespace App\Admin;


use App\Entity\ProProfil;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class ProProfilAdmin extends AbstractAdmin
{
    public function toString($object)
    {
        return $object instanceof ProProfil
            ? $object->getnom_entreprise()
            : 'Nom Entreprise';
    }

    protected function configureFormFields(FormMapper $form)
    {
        parent::configureFormFields($form); // TODO: Change the autogenerated stub
        $form
            ->add('nom_entreprise', TextType::class)
            ->add('mail', EmailType::class)
            ->add('adresse')
            ->add('ville')
            ->add('codepostal')
            ->add('nombredeplace')
            ->add('password', PasswordType::class)
        ;
    }

    protected function configureListFields(ListMapper $list)
    {
        parent::configureListFields($list); // TODO: Change the autogenerated stub
        $list
            ->addIdentifier('nom_entreprise')
            ->add('mail')
            ->add('adresse')
            ->add('ville')
            ->add('codepostal')
        ;
    }

    protected function configureDatagridFilters(DatagridMapper $filter)
    {
        parent::configureDatagridFilters($filter); // TODO: Change the autogenerated stub
        $filter
            ->add('nom_entreprise')
        ;
    }

}