<?php


namespace App\Admin;


use App\Entity\Tuteur;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;

class TuteurAdmin extends AbstractAdmin
{

    public function toString($object)
    {
        return $object instanceof Tuteur
            ? $object->getNom()
            : 'Nom';
    }

    protected function configureFormFields(FormMapper $form)
    {
        parent::configureFormFields($form); // TODO: Change the autogenerated stub
        $form
            ->add('nom', null, [
                'required' => true
            ])
            ->add('prenom')
        ;
    }

    protected function configureListFields(ListMapper $list)
    {
        parent::configureListFields($list); // TODO: Change the autogenerated stub
        $list
            ->addIdentifier('nom', null, [
                'route' => [
                    'name' => 'show'
                ]
            ])
            ->add('prenom')
            ->add('parentt', null, ['associated_property' => 'nom'])
            ->add('proProfil', null, ['associated_property' => 'nom_entreprise'])
            ->add('actions', 'actions', [
                'actions' => [
                    'edit' => [],
                    'delete' => []
                ]
            ])
        ;
    }

    protected function configureDatagridFilters(DatagridMapper $filter)
    {
        parent::configureDatagridFilters($filter); // TODO: Change the autogenerated stub
        $filter
            ->add('nom')
            ->add('prenom')
        ;
    }

    protected function configureShowFields(ShowMapper $show)
    {
        parent::configureShowFields($show); // TODO: Change the autogenerated stub
        $show
            ->add('nom')
            ->add('prenom')
            ->add('parentt', null, ['associated_property' => 'nom'])
            ->add('proProfil', null, ['associated_property' => 'nom_entreprise'])
            ->add('created_at')
            ->add('updated_at')
            ;
    }

}